config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    passwords:     'users/passwords' 
  }

  # 自分用プロフィール
  get  '/users/profile',      to: 'users#my_profile',   as: :show_user_profile
  get  '/users/profile/edit', to: 'users#edit_profile', as: :edit_user_profile

  # 他ユーザーのプロフィール表示
  resources :users, only: [:show, :edit, :update]
  resources :contacts, only: [:new, :create]


  resources :skill_offerings, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :reservations,    only: [:new, :create, :show, :index, :update, :destroy] do
    member do
      get   :approved
      patch :mark_completed
      patch :cancel
    end

    resource  :review, only: [:new, :create, :show]
    resources :messages, only: [:create]
  end

  root 'home#index'
  get 'home/index'
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  has_many :skill_offerings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :messages, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    set_flash_message!(:notice, :send_paranoid_instructions)
    redirect_to new_session_path(resource_name)
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  protected

  def after_sign_up_path_for(resource)
    edit_user_path(resource) # 登録後に編集画面へ
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new
    flash.discard(:alert)
    super
  end

  def create
    super
  end

  def destroy
    super
    flash.discard(:alert)
  end
  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update]

  def show
    @user = User.find(params[:id])
    @is_current_user = (@user == current_user)
  end

  def edit_profile
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user, notice: "プロフィールを更新しました！"
    else
      render :edit_profile
    end
  end

  private

  # user_params を一つにまとめ、:skill も許可する
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :image,
      :profile,
      :skill
    )
  end
end

app/views/users/edit_profile.html.erb
<!-- プロフィール編集画面 -->
<div class="container">
  <div class="edit-header">
    <h2>プロフィール編集</h2>
    <%= link_to "ユーザー詳細", edit_user_registration_path, class: "user-edit" %>
  </div>

  <%= form_with model: current_user,
                url: user_path(current_user),
                method: :patch,
                local: true,
                html: { multipart: true, id: 'profileForm' } do |f| %>

    <div class="form-group profile-image-group">
      <%= f.label :image, "アイコン画像", class: "form-label" %><br>

      <!-- プレビューも兼ねる既存の画像要素 -->
      <% if current_user.image.attached? %>
        <div class="current-image">
          <%= image_tag(
                current_user.image.variant(resize_to_limit: [120, 120]).processed,
                alt: "プロフィール画像",
                class: "profile-image",
                id: "currentProfileImage"
              ) %>
        </div>
      <% end %>

      <div class="image-upload-section">
        <div class="file-input-wrapper">
          <%= f.file_field :image,
                class: "file-input",
                accept: 'image/*',
                id: 'imageInput' %>
          <label for="imageInput" class="file-input-label">画像を選択</label>
        </div>
        <div class="upload-hint">
          JPG、PNG、GIF形式の画像をアップロードできます
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :profile, "自己紹介", class: "form-label" %><br>
      <%= f.text_area :profile,
                      rows: 5,
                      class: "form-control",
                      placeholder: "あなたについて教えてください" %>
    </div>

    <div class="form-group">
      <%= f.label :skill, "スキル", class: "form-label" %><br>
      <%= f.text_area :skill,
                      rows: 3,
                      class: "form-control",
                      placeholder: "例: TOEIC 850点、エンジニア歴など" %>
    </div>

    <div class="btn-group">
      <%= f.submit "更新する", class: "btn btn-primary" %>
      <%= link_to "戻る", user_path(current_user), class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<!-- プロフィール画面 -->

<div class="profile-wrapper">
  <div class="profile-card">
    <div class="profile-header">
      <h1>プロフィール</h1>
      <% if @user == current_user %>
        <%= link_to "編集", edit_user_profile_path, class: "profile-edit" %>
      <% end %>
    </div>

    <!-- プロフィール本文 -->
    <div class="profile-body">
      <!-- アイコンと名前 -->
      <div class="profile-info">
        <div class="profile-icon">
          <% if @user.image.attached? %>
            <%= image_tag @user.image.variant(resize_to_fill: [80, 80]), alt: "プロフィール画像", id: "currentProfileImage"%>
          <% else %>
            <span id="currentProfileImage"><%= @user.name.first(1) %></span>
          <% end %>
        </div>
        <h2 class="profile-name"><%= @user.name %></h2>
      </div>

      <!-- 自己紹介 -->
      <div class="section">
        <h3 class="section-title">自己紹介</h3>
        <p class="section-text">
          <%= @user.profile.presence || "よろしくお願いします" %>
        </p>
      </div>

      <!-- スキル -->
      <div class="section">
        <h3 class="section-title">スキル</h3>
        <div class="skills">
          <% if @user.skill.present? %>
            <p class="section-text"><%= @user.skill %></p>
          <% else %>
            <p class="text-gray-500">スキルが登録されていません</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>